theme: jekyll-theme-minimal
title: CIT 281 - Lab 1
description: In this project, I learned to install and setup your personal computer with the software tools required for this course, practiced using software tools, practice terminal or shell commands and keyboard shortcuts, and create my first Node.js server-side JavaScript file
